# VeRi-776 Vehicle Re-Identification Configuration

# Task and experiment settings
task_type: 'reid'
exp_name: 'veri776_dual_attention'
save_dir: './experiments/reid'
device: 'cuda'
seed: 42

# Model settings
model:
  backbone_name: 'deit_small_patch16_224'  # Use DeiT as per paper
  num_classes: 576  # Training vehicles (776 total - 200 test)
  embed_dim: 384
  num_heads: 6
  num_sa_blocks: 12
  num_glca_blocks: 1
  num_pwca_blocks: 12
  top_k_ratio: 0.3  # R=30% for GLCA as per paper
  drop_rate: 0.0
  drop_path_rate: 0.1
  img_size: 224

# Data settings
data:
  dataset_name: 'veri776'
  data_root: '/path/to/VeRi'
  batch_size: 64
  num_workers: 4
  image_size: [256, 256]  # Paper: 256x256 for vehicle datasets

# Training settings (matching paper exactly)
training:
  num_epochs: 120
  learning_rate: 0.008  # Paper: 0.008 for Re-ID
  weight_decay: 0.0001  # Paper: 1e-4
  optimizer: 'sgd'  # Paper uses SGD for Re-ID
  scheduler: 'cosine'
  momentum: 0.9
  num_instances: 4  # 4 images per vehicle ID
  triplet_margin: 0.3