# CUB-200-2011 Fine-Grained Visual Categorization Configuration

# Task and experiment settings
task_type: 'fgvc'
exp_name: 'cub200_dual_attention'
save_dir: './experiments/fgvc'
device: 'cuda'
seed: 42

# Model settings
model:
  backbone_name: 'deit_tiny_patch16_224.fb_in1k'  # Use DeiT as per paper
  num_classes: 200
  embed_dim: 192
  num_heads: 3
  num_sa_blocks: 12
  num_glca_blocks: 1
  num_pwca_blocks: 12
  top_k_ratio: 0.1  # R=10% for GLCA as per paper
  drop_rate: 0.0
  drop_path_rate: 0.1
  img_size: 448

# Data settings
data:
  dataset_name: 'cub200'
  data_root: '/home/mossbee/Work/Dataset/CUB_200_2011/CUB_200_2011'
  batch_size: 16
  num_workers: 4
  image_size: [448, 448]  # Paper: 448x448 for training and test

# Training settings  
training:
  num_epochs: 100
  learning_rate: 0.0005  # Paper uses lr_scaled = 5e-4/512 * batch_size
  weight_decay: 0.05
  optimizer: 'adam'  # Paper uses Adam
  scheduler: 'cosine'
  warmup_epochs: 5
  min_lr: 1e-6

